// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Models;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(VoteDBContext))]
    [Migration("20200811142215_seedInitialCandidateData6")]
    partial class seedInitialCandidateData6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication1.Models.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ElectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VoterBeingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isNeutralOpinion")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.HasIndex("VoterBeingId");

                    b.ToTable("Candidate");

                    b.HasData(
                        new
                        {
                            Id = new Guid("beb19f42-63b1-45ec-bf80-a8a7cd381a65"),
                            ElectionId = new Guid("ef62cf71-3892-4f12-8f54-4a80580eb3b0"),
                            VoterBeingId = new Guid("8dd6ebe1-e2e4-4555-ac61-9887cebebf61"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("317760ab-9fcd-42ec-85de-0631d3b7356c"),
                            ElectionId = new Guid("ef62cf71-3892-4f12-8f54-4a80580eb3b0"),
                            VoterBeingId = new Guid("df4b1285-b216-488c-88b7-0de75528f2fc"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("aaf78762-1576-4f60-8593-b0de7303a1c9"),
                            ElectionId = new Guid("ef62cf71-3892-4f12-8f54-4a80580eb3b0"),
                            VoterBeingId = new Guid("c81388cf-be3e-42fc-b791-02eccce16095"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("bc2007e6-51b6-49b0-992f-fdc977d3ae1c"),
                            ElectionId = new Guid("ef62cf71-3892-4f12-8f54-4a80580eb3b0"),
                            VoterBeingId = new Guid("4ff2b64f-17fe-4621-9310-eeb59a9af847"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("36e9af62-c6b2-439f-b850-ee7084cfde42"),
                            ElectionId = new Guid("ef62cf71-3892-4f12-8f54-4a80580eb3b0"),
                            VoterBeingId = new Guid("e61f81ab-a991-4298-b668-c973a5b75dc9"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("2ba62cf5-85a5-415c-913e-f313fb0c143c"),
                            ElectionId = new Guid("c71e21c7-3c87-4aea-bf8d-2be8edc8722a"),
                            VoterBeingId = new Guid("c81388cf-be3e-42fc-b791-02eccce16095"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("a8926c2a-01da-49e9-955b-5ab53fbfa7fe"),
                            ElectionId = new Guid("c71e21c7-3c87-4aea-bf8d-2be8edc8722a"),
                            VoterBeingId = new Guid("4ff2b64f-17fe-4621-9310-eeb59a9af847"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("338557b1-43f2-4ab4-9a8c-1bd30cc5712d"),
                            ElectionId = new Guid("c71e21c7-3c87-4aea-bf8d-2be8edc8722a"),
                            VoterBeingId = new Guid("e61f81ab-a991-4298-b668-c973a5b75dc9"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("9d97bf6e-e986-45f5-ba6b-38a6e50ba6ec"),
                            ElectionId = new Guid("6d1ac165-5488-4f86-84ad-47301d813802"),
                            VoterBeingId = new Guid("c81388cf-be3e-42fc-b791-02eccce16095"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("ea2534cd-0a2b-4eb6-b3bd-2d752b2903b1"),
                            ElectionId = new Guid("6d1ac165-5488-4f86-84ad-47301d813802"),
                            VoterBeingId = new Guid("4ff2b64f-17fe-4621-9310-eeb59a9af847"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("eb789035-af8e-41f4-a8b4-c63839ea76b4"),
                            ElectionId = new Guid("76daa454-e061-46ac-ba1e-4c09fdcd418e"),
                            VoterBeingId = new Guid("e61f81ab-a991-4298-b668-c973a5b75dc9"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("25748fa5-1d69-441f-9deb-2f927c5e95f8"),
                            ElectionId = new Guid("76daa454-e061-46ac-ba1e-4c09fdcd418e"),
                            VoterBeingId = new Guid("1d6d6442-25ac-4cf9-aa44-0d91622a4927"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("06d98284-629c-493d-aa06-46a5008e1696"),
                            ElectionId = new Guid("76daa454-e061-46ac-ba1e-4c09fdcd418e"),
                            VoterBeingId = new Guid("62ae0555-718d-4623-a12a-7ae4a2e26aef"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("42acb95f-d02c-4c62-b3c3-c3c7dc59b192"),
                            ElectionId = new Guid("76daa454-e061-46ac-ba1e-4c09fdcd418e"),
                            VoterBeingId = new Guid("6c9de511-db59-4be8-9315-d58700ce10be"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("974c2553-a3ab-4a63-bdaf-1018630f8f59"),
                            ElectionId = new Guid("40556dbd-b5ae-47af-89eb-32deee130dd9"),
                            VoterBeingId = new Guid("cd285ce6-b6e9-4933-8e07-6d50e0251788"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("f1c7d2f6-e23e-4398-a1db-794d398c0ea3"),
                            ElectionId = new Guid("40556dbd-b5ae-47af-89eb-32deee130dd9"),
                            VoterBeingId = new Guid("d454ae67-913e-4f7b-82c1-4da539737199"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("e373f311-ffc4-4a88-8360-1762d638930b"),
                            ElectionId = new Guid("40556dbd-b5ae-47af-89eb-32deee130dd9"),
                            VoterBeingId = new Guid("18537eea-e8f8-49cd-8ddf-10646c9a9f21"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("4225bbeb-5321-4ed0-9163-cb2ebea3eb67"),
                            ElectionId = new Guid("40556dbd-b5ae-47af-89eb-32deee130dd9"),
                            VoterBeingId = new Guid("d789a80a-493f-4248-90b0-35edab1c3c63"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("df494a48-38ac-4c53-8df6-7bc26aa760ff"),
                            ElectionId = new Guid("40556dbd-b5ae-47af-89eb-32deee130dd9"),
                            VoterBeingId = new Guid("71ad22cf-168a-40be-9867-4a7ebe34c339"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("875c1b24-8287-40f2-9686-421544795564"),
                            ElectionId = new Guid("42c5a090-b3bd-4b0b-9de4-48f987d8346e"),
                            VoterBeingId = new Guid("e61f81ab-a991-4298-b668-c973a5b75dc9"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("cf67c200-e5f1-4017-937d-cd3cb2ac7a78"),
                            ElectionId = new Guid("42c5a090-b3bd-4b0b-9de4-48f987d8346e"),
                            VoterBeingId = new Guid("1d6d6442-25ac-4cf9-aa44-0d91622a4927"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("43fe0843-3607-4f14-af03-6195bf5f8760"),
                            ElectionId = new Guid("42c5a090-b3bd-4b0b-9de4-48f987d8346e"),
                            VoterBeingId = new Guid("62ae0555-718d-4623-a12a-7ae4a2e26aef"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("8b2947e3-f56f-4035-afcb-e04fd497063a"),
                            ElectionId = new Guid("42c5a090-b3bd-4b0b-9de4-48f987d8346e"),
                            VoterBeingId = new Guid("6c9de511-db59-4be8-9315-d58700ce10be"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("2e372dbe-2927-4767-a2bb-3558069beb0e"),
                            ElectionId = new Guid("442530b2-3e0a-4fc1-995d-1da1c6cb55cc"),
                            VoterBeingId = new Guid("8dd6ebe1-e2e4-4555-ac61-9887cebebf61"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("ea0efdaa-d579-44ec-a223-38f70bc2f570"),
                            ElectionId = new Guid("442530b2-3e0a-4fc1-995d-1da1c6cb55cc"),
                            VoterBeingId = new Guid("df4b1285-b216-488c-88b7-0de75528f2fc"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("27c6ba1f-0170-4fbf-ad91-32f022975cbf"),
                            ElectionId = new Guid("442530b2-3e0a-4fc1-995d-1da1c6cb55cc"),
                            VoterBeingId = new Guid("c81388cf-be3e-42fc-b791-02eccce16095"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("1ba784f8-e0ef-491d-a451-e3ffc06dbf3e"),
                            ElectionId = new Guid("442530b2-3e0a-4fc1-995d-1da1c6cb55cc"),
                            VoterBeingId = new Guid("4ff2b64f-17fe-4621-9310-eeb59a9af847"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("73d29d97-35c5-4194-9683-2df0a0b6b390"),
                            ElectionId = new Guid("442530b2-3e0a-4fc1-995d-1da1c6cb55cc"),
                            VoterBeingId = new Guid("e61f81ab-a991-4298-b668-c973a5b75dc9"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("d06219da-1725-494a-9f7c-2653d9087ab6"),
                            ElectionId = new Guid("f8899970-5057-4a23-833c-dc75ee84c8d2"),
                            VoterBeingId = new Guid("c81388cf-be3e-42fc-b791-02eccce16095"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("fba05cfd-4d29-4c03-ad68-c58b094d5e87"),
                            ElectionId = new Guid("f8899970-5057-4a23-833c-dc75ee84c8d2"),
                            VoterBeingId = new Guid("4ff2b64f-17fe-4621-9310-eeb59a9af847"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("919cfb2c-580a-4079-90f5-f3ae967b672b"),
                            ElectionId = new Guid("f8899970-5057-4a23-833c-dc75ee84c8d2"),
                            VoterBeingId = new Guid("e61f81ab-a991-4298-b668-c973a5b75dc9"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("56e347ac-7a53-4080-95d7-b4e87ecdefb2"),
                            ElectionId = new Guid("b6ea83b1-3cbe-47ed-bf25-9abc8dac9644"),
                            VoterBeingId = new Guid("c81388cf-be3e-42fc-b791-02eccce16095"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("56618227-52a4-4a21-9819-b3f48fb68bbf"),
                            ElectionId = new Guid("b6ea83b1-3cbe-47ed-bf25-9abc8dac9644"),
                            VoterBeingId = new Guid("4ff2b64f-17fe-4621-9310-eeb59a9af847"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("caa965c1-d725-4ed2-929b-1827c12e707b"),
                            ElectionId = new Guid("cfd1f2a9-3984-42a0-8ec1-26fd4eef0ead"),
                            VoterBeingId = new Guid("e61f81ab-a991-4298-b668-c973a5b75dc9"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("5d5adec0-00e7-4b6e-b0b4-05851cdda9d8"),
                            ElectionId = new Guid("cfd1f2a9-3984-42a0-8ec1-26fd4eef0ead"),
                            VoterBeingId = new Guid("1d6d6442-25ac-4cf9-aa44-0d91622a4927"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("b4627729-5bb8-4f5c-8f6b-7cb0e06ad406"),
                            ElectionId = new Guid("cfd1f2a9-3984-42a0-8ec1-26fd4eef0ead"),
                            VoterBeingId = new Guid("62ae0555-718d-4623-a12a-7ae4a2e26aef"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("ccf8b96e-1297-4839-8d41-c35a117dc8e6"),
                            ElectionId = new Guid("cfd1f2a9-3984-42a0-8ec1-26fd4eef0ead"),
                            VoterBeingId = new Guid("6c9de511-db59-4be8-9315-d58700ce10be"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("2fe358a7-f2d4-4d48-97b2-e58764539830"),
                            ElectionId = new Guid("bbcd22cb-dc43-4ea2-854c-acb61564699c"),
                            VoterBeingId = new Guid("cd285ce6-b6e9-4933-8e07-6d50e0251788"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("5d58bff5-14d1-403f-b6c4-47779dcc8622"),
                            ElectionId = new Guid("bbcd22cb-dc43-4ea2-854c-acb61564699c"),
                            VoterBeingId = new Guid("d454ae67-913e-4f7b-82c1-4da539737199"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("958e6e3b-4ddf-4f09-9a3a-1d6fa746ecaa"),
                            ElectionId = new Guid("bbcd22cb-dc43-4ea2-854c-acb61564699c"),
                            VoterBeingId = new Guid("18537eea-e8f8-49cd-8ddf-10646c9a9f21"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("9a38e1d1-b5ad-4959-940b-a8c212f04996"),
                            ElectionId = new Guid("bbcd22cb-dc43-4ea2-854c-acb61564699c"),
                            VoterBeingId = new Guid("d789a80a-493f-4248-90b0-35edab1c3c63"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("2020db60-310d-42ec-b6d3-107942583f6f"),
                            ElectionId = new Guid("bbcd22cb-dc43-4ea2-854c-acb61564699c"),
                            VoterBeingId = new Guid("71ad22cf-168a-40be-9867-4a7ebe34c339"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("87ce555e-9ae7-4127-8fa5-af423df9dc9a"),
                            ElectionId = new Guid("b798676d-750e-4950-a527-5ccbc17004a4"),
                            VoterBeingId = new Guid("e61f81ab-a991-4298-b668-c973a5b75dc9"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("1634d34b-0e45-4731-a019-28b0582bd6a5"),
                            ElectionId = new Guid("b798676d-750e-4950-a527-5ccbc17004a4"),
                            VoterBeingId = new Guid("1d6d6442-25ac-4cf9-aa44-0d91622a4927"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("128c6749-994a-44e6-b445-f6a3e26d2a03"),
                            ElectionId = new Guid("b798676d-750e-4950-a527-5ccbc17004a4"),
                            VoterBeingId = new Guid("62ae0555-718d-4623-a12a-7ae4a2e26aef"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("c151f1a8-26e5-4b31-9234-fd8405374235"),
                            ElectionId = new Guid("b798676d-750e-4950-a527-5ccbc17004a4"),
                            VoterBeingId = new Guid("6c9de511-db59-4be8-9315-d58700ce10be"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("3be3ad44-211b-4206-8fde-353ec7b8e526"),
                            ElectionId = new Guid("33e5e889-f44b-461a-83c9-680f34f82e06"),
                            VoterBeingId = new Guid("e61f81ab-a991-4298-b668-c973a5b75dc9"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("0500016d-c3c1-41dd-9013-f450cf5e8110"),
                            ElectionId = new Guid("33e5e889-f44b-461a-83c9-680f34f82e06"),
                            VoterBeingId = new Guid("1d6d6442-25ac-4cf9-aa44-0d91622a4927"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("75ecc207-2d6d-4abb-86ba-f26c6129d93c"),
                            ElectionId = new Guid("33e5e889-f44b-461a-83c9-680f34f82e06"),
                            VoterBeingId = new Guid("62ae0555-718d-4623-a12a-7ae4a2e26aef"),
                            isNeutralOpinion = false
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Election", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DurationInDays")
                        .HasColumnType("int");

                    b.Property<bool>("HasNeutral")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Election");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ef62cf71-3892-4f12-8f54-4a80580eb3b0"),
                            DurationInDays = 3,
                            HasNeutral = false,
                            Name = "Election Test 1",
                            StartDate = new DateTime(2011, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c71e21c7-3c87-4aea-bf8d-2be8edc8722a"),
                            DurationInDays = 3,
                            HasNeutral = false,
                            Name = "Election Test 2",
                            StartDate = new DateTime(2012, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6d1ac165-5488-4f86-84ad-47301d813802"),
                            DurationInDays = 3,
                            HasNeutral = false,
                            Name = "Election Test 3",
                            StartDate = new DateTime(2013, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("76daa454-e061-46ac-ba1e-4c09fdcd418e"),
                            DurationInDays = 3,
                            HasNeutral = false,
                            Name = "Election Test 4",
                            StartDate = new DateTime(2014, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("40556dbd-b5ae-47af-89eb-32deee130dd9"),
                            DurationInDays = 3,
                            HasNeutral = false,
                            Name = "Election Test 5",
                            StartDate = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("42c5a090-b3bd-4b0b-9de4-48f987d8346e"),
                            DurationInDays = 3,
                            HasNeutral = false,
                            Name = "Election Test 6",
                            StartDate = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("442530b2-3e0a-4fc1-995d-1da1c6cb55cc"),
                            DurationInDays = 3,
                            HasNeutral = false,
                            Name = "Election Test 7",
                            StartDate = new DateTime(2017, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f8899970-5057-4a23-833c-dc75ee84c8d2"),
                            DurationInDays = 3,
                            HasNeutral = false,
                            Name = "Election Test 8",
                            StartDate = new DateTime(2018, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b6ea83b1-3cbe-47ed-bf25-9abc8dac9644"),
                            DurationInDays = 3,
                            HasNeutral = false,
                            Name = "Election Test 9",
                            StartDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("cfd1f2a9-3984-42a0-8ec1-26fd4eef0ead"),
                            DurationInDays = 3,
                            HasNeutral = false,
                            Name = "Election Test 10",
                            StartDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("bbcd22cb-dc43-4ea2-854c-acb61564699c"),
                            DurationInDays = 3,
                            HasNeutral = false,
                            Name = "Election Test 11",
                            StartDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b798676d-750e-4950-a527-5ccbc17004a4"),
                            DurationInDays = 3,
                            HasNeutral = false,
                            Name = "Election Test 12",
                            StartDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("33e5e889-f44b-461a-83c9-680f34f82e06"),
                            DurationInDays = 3,
                            HasNeutral = false,
                            Name = "Election Test 13",
                            StartDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.State", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("State");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fa9b72ee-dfcc-4353-b195-5c2855b1343f"),
                            Name = "Oran"
                        },
                        new
                        {
                            Id = new Guid("32065802-7f25-47bc-8987-dd4fdb2829c4"),
                            Name = "Meca"
                        },
                        new
                        {
                            Id = new Guid("3138e047-e80f-44a1-ae1d-96804784f807"),
                            Name = "Cairo"
                        },
                        new
                        {
                            Id = new Guid("33f88529-1a04-4d5e-84dc-135646948bc0"),
                            Name = "ElQuds"
                        },
                        new
                        {
                            Id = new Guid("918333ff-ac52-4424-a3d9-09bee4c39b91"),
                            Name = "Algiers"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Vote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Datetime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ElectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VoterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("ElectionId");

                    b.HasIndex("VoterId");

                    b.ToTable("Vote");
                });

            modelBuilder.Entity("WebApplication1.Models.Voter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("Voter");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0d925194-fee5-4750-a53c-b36a47afeeab"),
                            FirstName = "Hamza",
                            LastName = "Dahmoun",
                            StateId = new Guid("fa9b72ee-dfcc-4353-b195-5c2855b1343f"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("8dd6ebe1-e2e4-4555-ac61-9887cebebf61"),
                            FirstName = "Ikram",
                            LastName = "Dahmoun",
                            StateId = new Guid("fa9b72ee-dfcc-4353-b195-5c2855b1343f"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("df4b1285-b216-488c-88b7-0de75528f2fc"),
                            FirstName = "Ahmed",
                            LastName = "Mohamed",
                            StateId = new Guid("fa9b72ee-dfcc-4353-b195-5c2855b1343f"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("c81388cf-be3e-42fc-b791-02eccce16095"),
                            FirstName = "Mohamed",
                            LastName = "Zitouni",
                            StateId = new Guid("32065802-7f25-47bc-8987-dd4fdb2829c4"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("4ff2b64f-17fe-4621-9310-eeb59a9af847"),
                            FirstName = "Yasser",
                            LastName = "Zitouni",
                            StateId = new Guid("32065802-7f25-47bc-8987-dd4fdb2829c4"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("e61f81ab-a991-4298-b668-c973a5b75dc9"),
                            FirstName = "Larbi",
                            LastName = "Fkaier",
                            StateId = new Guid("32065802-7f25-47bc-8987-dd4fdb2829c4"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("1d6d6442-25ac-4cf9-aa44-0d91622a4927"),
                            FirstName = "Djamel",
                            LastName = "Tahraoui",
                            StateId = new Guid("32065802-7f25-47bc-8987-dd4fdb2829c4"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("62ae0555-718d-4623-a12a-7ae4a2e26aef"),
                            FirstName = "Sidahmed",
                            LastName = "Dahmoun",
                            StateId = new Guid("3138e047-e80f-44a1-ae1d-96804784f807"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("6c9de511-db59-4be8-9315-d58700ce10be"),
                            FirstName = "Bilal",
                            LastName = "Dahmoun",
                            StateId = new Guid("3138e047-e80f-44a1-ae1d-96804784f807"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("cd285ce6-b6e9-4933-8e07-6d50e0251788"),
                            FirstName = "Maria",
                            LastName = "Hafsa",
                            StateId = new Guid("33f88529-1a04-4d5e-84dc-135646948bc0"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("d454ae67-913e-4f7b-82c1-4da539737199"),
                            FirstName = "Brahim",
                            LastName = "Roudjai",
                            StateId = new Guid("33f88529-1a04-4d5e-84dc-135646948bc0"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("18537eea-e8f8-49cd-8ddf-10646c9a9f21"),
                            FirstName = "Amine",
                            LastName = "Brahem",
                            StateId = new Guid("33f88529-1a04-4d5e-84dc-135646948bc0"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("d789a80a-493f-4248-90b0-35edab1c3c63"),
                            FirstName = "Azzedine",
                            LastName = "Brahmi",
                            StateId = new Guid("3138e047-e80f-44a1-ae1d-96804784f807"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("71ad22cf-168a-40be-9867-4a7ebe34c339"),
                            FirstName = "Mohamed",
                            LastName = "Chikhi",
                            StateId = new Guid("918333ff-ac52-4424-a3d9-09bee4c39b91"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("783118b1-111d-4c6e-b75e-dcd721ccfc2c"),
                            FirstName = "Mahmoud",
                            LastName = "Dahmoun",
                            StateId = new Guid("918333ff-ac52-4424-a3d9-09bee4c39b91"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("0642267b-8df3-405d-b596-e50c2cdeefde"),
                            FirstName = "Lakhdar",
                            LastName = "Zitouni",
                            StateId = new Guid("918333ff-ac52-4424-a3d9-09bee4c39b91"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Candidate", b =>
                {
                    b.HasOne("WebApplication1.Models.Election", "Election")
                        .WithMany("Candidates")
                        .HasForeignKey("ElectionId");

                    b.HasOne("WebApplication1.Models.Voter", "VoterBeing")
                        .WithMany()
                        .HasForeignKey("VoterBeingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApplication1.Models.Vote", b =>
                {
                    b.HasOne("WebApplication1.Models.Candidate", "Candidate")
                        .WithMany("Votes")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.Election", "Election")
                        .WithMany("Votes")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.Voter", "Voter")
                        .WithMany("Votes")
                        .HasForeignKey("VoterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApplication1.Models.Voter", b =>
                {
                    b.HasOne("WebApplication1.Models.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
