// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Models;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(VoteDBContext))]
    [Migration("20200811151259_seedInitialVoteData")]
    partial class seedInitialVoteData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication1.Models.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ElectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VoterBeingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isNeutralOpinion")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.HasIndex("VoterBeingId");

                    b.ToTable("Candidate");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8bc92480-c3d1-440d-86c4-a6a4ed89255a"),
                            ElectionId = new Guid("ef62cf71-3892-4f12-8f54-4a80580eb3b0"),
                            VoterBeingId = new Guid("8dd6ebe1-e2e4-4555-ac61-9887cebebf61"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("0d201c31-b90f-4721-98ce-03f7806a1d2d"),
                            ElectionId = new Guid("ef62cf71-3892-4f12-8f54-4a80580eb3b0"),
                            VoterBeingId = new Guid("df4b1285-b216-488c-88b7-0de75528f2fc"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("87945fcb-6b98-4a17-99d6-0611606fb203"),
                            ElectionId = new Guid("ef62cf71-3892-4f12-8f54-4a80580eb3b0"),
                            VoterBeingId = new Guid("c81388cf-be3e-42fc-b791-02eccce16095"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("b58d1bf6-a210-40e1-a745-6bade04019a7"),
                            ElectionId = new Guid("ef62cf71-3892-4f12-8f54-4a80580eb3b0"),
                            VoterBeingId = new Guid("4ff2b64f-17fe-4621-9310-eeb59a9af847"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("0f2088c2-06d8-4913-9986-c44473b50f2b"),
                            ElectionId = new Guid("ef62cf71-3892-4f12-8f54-4a80580eb3b0"),
                            VoterBeingId = new Guid("e61f81ab-a991-4298-b668-c973a5b75dc9"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("2c9b8405-39bc-4bc8-b539-a473122eb007"),
                            ElectionId = new Guid("c71e21c7-3c87-4aea-bf8d-2be8edc8722a"),
                            VoterBeingId = new Guid("c81388cf-be3e-42fc-b791-02eccce16095"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("43b303b1-630e-4dd6-811b-63f88c06e60d"),
                            ElectionId = new Guid("c71e21c7-3c87-4aea-bf8d-2be8edc8722a"),
                            VoterBeingId = new Guid("4ff2b64f-17fe-4621-9310-eeb59a9af847"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("470ac0b5-151c-43a2-bbd8-af80f38d9435"),
                            ElectionId = new Guid("c71e21c7-3c87-4aea-bf8d-2be8edc8722a"),
                            VoterBeingId = new Guid("e61f81ab-a991-4298-b668-c973a5b75dc9"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("cb6e54e2-77a0-4f31-96f4-4ef31fee2d24"),
                            ElectionId = new Guid("6d1ac165-5488-4f86-84ad-47301d813802"),
                            VoterBeingId = new Guid("c81388cf-be3e-42fc-b791-02eccce16095"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("69da0af1-b243-439b-a227-95cec2ed4350"),
                            ElectionId = new Guid("6d1ac165-5488-4f86-84ad-47301d813802"),
                            VoterBeingId = new Guid("4ff2b64f-17fe-4621-9310-eeb59a9af847"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("c877feb9-c8a2-42de-80c0-196410a60196"),
                            ElectionId = new Guid("76daa454-e061-46ac-ba1e-4c09fdcd418e"),
                            VoterBeingId = new Guid("e61f81ab-a991-4298-b668-c973a5b75dc9"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("e194ac0c-a0d0-48ec-a3a6-25b9f6a07587"),
                            ElectionId = new Guid("76daa454-e061-46ac-ba1e-4c09fdcd418e"),
                            VoterBeingId = new Guid("1d6d6442-25ac-4cf9-aa44-0d91622a4927"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("556e2593-197d-4c40-a1a7-159917816196"),
                            ElectionId = new Guid("76daa454-e061-46ac-ba1e-4c09fdcd418e"),
                            VoterBeingId = new Guid("62ae0555-718d-4623-a12a-7ae4a2e26aef"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("2bdb3acd-e9b7-40a0-b2ea-d958f59c3b6c"),
                            ElectionId = new Guid("76daa454-e061-46ac-ba1e-4c09fdcd418e"),
                            VoterBeingId = new Guid("6c9de511-db59-4be8-9315-d58700ce10be"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("ea0eefce-3b8e-4a33-9af9-524ba5c678ee"),
                            ElectionId = new Guid("40556dbd-b5ae-47af-89eb-32deee130dd9"),
                            VoterBeingId = new Guid("cd285ce6-b6e9-4933-8e07-6d50e0251788"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("575d00a6-b8e1-4b71-ba9e-4d26490d4d84"),
                            ElectionId = new Guid("40556dbd-b5ae-47af-89eb-32deee130dd9"),
                            VoterBeingId = new Guid("d454ae67-913e-4f7b-82c1-4da539737199"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("473f81e3-aa8b-457a-9d83-cffb1d277dec"),
                            ElectionId = new Guid("40556dbd-b5ae-47af-89eb-32deee130dd9"),
                            VoterBeingId = new Guid("18537eea-e8f8-49cd-8ddf-10646c9a9f21"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("62055ca5-e962-4fff-b32d-48d7c71f9f23"),
                            ElectionId = new Guid("40556dbd-b5ae-47af-89eb-32deee130dd9"),
                            VoterBeingId = new Guid("d789a80a-493f-4248-90b0-35edab1c3c63"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("701bd96b-02e4-47af-92f4-d1e49951a2dc"),
                            ElectionId = new Guid("40556dbd-b5ae-47af-89eb-32deee130dd9"),
                            VoterBeingId = new Guid("71ad22cf-168a-40be-9867-4a7ebe34c339"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("1590c51e-7122-48e3-bcd1-12a43e170ede"),
                            ElectionId = new Guid("42c5a090-b3bd-4b0b-9de4-48f987d8346e"),
                            VoterBeingId = new Guid("e61f81ab-a991-4298-b668-c973a5b75dc9"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("950a79f2-bed6-40e1-8cb6-6d89ab553188"),
                            ElectionId = new Guid("42c5a090-b3bd-4b0b-9de4-48f987d8346e"),
                            VoterBeingId = new Guid("1d6d6442-25ac-4cf9-aa44-0d91622a4927"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("a5452366-7898-47cd-a5bb-0e4a95ed319b"),
                            ElectionId = new Guid("42c5a090-b3bd-4b0b-9de4-48f987d8346e"),
                            VoterBeingId = new Guid("62ae0555-718d-4623-a12a-7ae4a2e26aef"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("fda62639-faf3-4178-90fe-7da3484c48af"),
                            ElectionId = new Guid("42c5a090-b3bd-4b0b-9de4-48f987d8346e"),
                            VoterBeingId = new Guid("6c9de511-db59-4be8-9315-d58700ce10be"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("943633be-4f99-44d1-b9cf-04434f03fc6d"),
                            ElectionId = new Guid("442530b2-3e0a-4fc1-995d-1da1c6cb55cc"),
                            VoterBeingId = new Guid("8dd6ebe1-e2e4-4555-ac61-9887cebebf61"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("7f2811bc-48df-478d-83ad-649a7e2a8195"),
                            ElectionId = new Guid("442530b2-3e0a-4fc1-995d-1da1c6cb55cc"),
                            VoterBeingId = new Guid("df4b1285-b216-488c-88b7-0de75528f2fc"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("a49e5a59-c2b5-451f-a620-425adec7c44d"),
                            ElectionId = new Guid("442530b2-3e0a-4fc1-995d-1da1c6cb55cc"),
                            VoterBeingId = new Guid("c81388cf-be3e-42fc-b791-02eccce16095"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("910fb488-8da3-4183-a92a-17d046d59553"),
                            ElectionId = new Guid("442530b2-3e0a-4fc1-995d-1da1c6cb55cc"),
                            VoterBeingId = new Guid("4ff2b64f-17fe-4621-9310-eeb59a9af847"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("85c45467-32c4-4dae-8023-06df1df955b4"),
                            ElectionId = new Guid("442530b2-3e0a-4fc1-995d-1da1c6cb55cc"),
                            VoterBeingId = new Guid("e61f81ab-a991-4298-b668-c973a5b75dc9"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("342a2bbc-d9ec-41d8-b45d-91ffa59975b2"),
                            ElectionId = new Guid("f8899970-5057-4a23-833c-dc75ee84c8d2"),
                            VoterBeingId = new Guid("c81388cf-be3e-42fc-b791-02eccce16095"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("c0e68551-3e5e-4268-89e9-b6310de3956b"),
                            ElectionId = new Guid("f8899970-5057-4a23-833c-dc75ee84c8d2"),
                            VoterBeingId = new Guid("4ff2b64f-17fe-4621-9310-eeb59a9af847"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("6c44ea03-afa1-4546-94fa-0cf086293fc2"),
                            ElectionId = new Guid("f8899970-5057-4a23-833c-dc75ee84c8d2"),
                            VoterBeingId = new Guid("e61f81ab-a991-4298-b668-c973a5b75dc9"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("80cd8f07-8c6e-4279-b62e-9883aedf0d56"),
                            ElectionId = new Guid("b6ea83b1-3cbe-47ed-bf25-9abc8dac9644"),
                            VoterBeingId = new Guid("c81388cf-be3e-42fc-b791-02eccce16095"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("ba5a0188-6983-40d9-9364-9113509e97ee"),
                            ElectionId = new Guid("b6ea83b1-3cbe-47ed-bf25-9abc8dac9644"),
                            VoterBeingId = new Guid("4ff2b64f-17fe-4621-9310-eeb59a9af847"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("e139e024-45d8-4e24-83fb-1b394bd458cb"),
                            ElectionId = new Guid("cfd1f2a9-3984-42a0-8ec1-26fd4eef0ead"),
                            VoterBeingId = new Guid("e61f81ab-a991-4298-b668-c973a5b75dc9"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("3a884c97-5e90-4e3d-87c0-5d96745e54a9"),
                            ElectionId = new Guid("cfd1f2a9-3984-42a0-8ec1-26fd4eef0ead"),
                            VoterBeingId = new Guid("1d6d6442-25ac-4cf9-aa44-0d91622a4927"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("0bc40cad-00fe-4ca8-a789-91b59f0c5a2f"),
                            ElectionId = new Guid("cfd1f2a9-3984-42a0-8ec1-26fd4eef0ead"),
                            VoterBeingId = new Guid("62ae0555-718d-4623-a12a-7ae4a2e26aef"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("ea67fb4e-329b-4340-9a71-2fb944461ca5"),
                            ElectionId = new Guid("cfd1f2a9-3984-42a0-8ec1-26fd4eef0ead"),
                            VoterBeingId = new Guid("6c9de511-db59-4be8-9315-d58700ce10be"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("dd50e713-110f-4ea5-91a2-9144d95cc1fa"),
                            ElectionId = new Guid("bbcd22cb-dc43-4ea2-854c-acb61564699c"),
                            VoterBeingId = new Guid("cd285ce6-b6e9-4933-8e07-6d50e0251788"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("5d1858eb-06f1-40a4-ad71-04f5f2ec37bf"),
                            ElectionId = new Guid("bbcd22cb-dc43-4ea2-854c-acb61564699c"),
                            VoterBeingId = new Guid("d454ae67-913e-4f7b-82c1-4da539737199"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("08828a2a-b8aa-4c7e-be3a-7961b8e40daf"),
                            ElectionId = new Guid("bbcd22cb-dc43-4ea2-854c-acb61564699c"),
                            VoterBeingId = new Guid("18537eea-e8f8-49cd-8ddf-10646c9a9f21"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("0668f926-7d1f-4f3d-b0a0-3dbc90357eb7"),
                            ElectionId = new Guid("bbcd22cb-dc43-4ea2-854c-acb61564699c"),
                            VoterBeingId = new Guid("d789a80a-493f-4248-90b0-35edab1c3c63"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("83c9cd1b-4212-426b-985f-1770676c0be9"),
                            ElectionId = new Guid("bbcd22cb-dc43-4ea2-854c-acb61564699c"),
                            VoterBeingId = new Guid("71ad22cf-168a-40be-9867-4a7ebe34c339"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("73da9cde-8eed-4743-b369-8cb2280e4278"),
                            ElectionId = new Guid("b798676d-750e-4950-a527-5ccbc17004a4"),
                            VoterBeingId = new Guid("e61f81ab-a991-4298-b668-c973a5b75dc9"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("2548f0bc-8005-42cc-a938-dd9c19b29216"),
                            ElectionId = new Guid("b798676d-750e-4950-a527-5ccbc17004a4"),
                            VoterBeingId = new Guid("1d6d6442-25ac-4cf9-aa44-0d91622a4927"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("b2b4e50f-ad7d-4736-8d9d-5067b7a4f173"),
                            ElectionId = new Guid("b798676d-750e-4950-a527-5ccbc17004a4"),
                            VoterBeingId = new Guid("62ae0555-718d-4623-a12a-7ae4a2e26aef"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("e3bdc2bb-b5d0-4b0b-b187-3e43454f5f34"),
                            ElectionId = new Guid("b798676d-750e-4950-a527-5ccbc17004a4"),
                            VoterBeingId = new Guid("6c9de511-db59-4be8-9315-d58700ce10be"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("be668d55-1706-4f8b-98eb-c0af8a7341fe"),
                            ElectionId = new Guid("33e5e889-f44b-461a-83c9-680f34f82e06"),
                            VoterBeingId = new Guid("e61f81ab-a991-4298-b668-c973a5b75dc9"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("15ca3802-01d6-4f7d-beef-fb99a6485606"),
                            ElectionId = new Guid("33e5e889-f44b-461a-83c9-680f34f82e06"),
                            VoterBeingId = new Guid("1d6d6442-25ac-4cf9-aa44-0d91622a4927"),
                            isNeutralOpinion = false
                        },
                        new
                        {
                            Id = new Guid("224cdcc9-ae8e-4668-b88a-ceb9e3927594"),
                            ElectionId = new Guid("33e5e889-f44b-461a-83c9-680f34f82e06"),
                            VoterBeingId = new Guid("62ae0555-718d-4623-a12a-7ae4a2e26aef"),
                            isNeutralOpinion = false
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Election", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DurationInDays")
                        .HasColumnType("int");

                    b.Property<bool>("HasNeutral")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Election");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ef62cf71-3892-4f12-8f54-4a80580eb3b0"),
                            DurationInDays = 3,
                            HasNeutral = false,
                            Name = "Election Test 1",
                            StartDate = new DateTime(2011, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c71e21c7-3c87-4aea-bf8d-2be8edc8722a"),
                            DurationInDays = 3,
                            HasNeutral = false,
                            Name = "Election Test 2",
                            StartDate = new DateTime(2012, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6d1ac165-5488-4f86-84ad-47301d813802"),
                            DurationInDays = 3,
                            HasNeutral = false,
                            Name = "Election Test 3",
                            StartDate = new DateTime(2013, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("76daa454-e061-46ac-ba1e-4c09fdcd418e"),
                            DurationInDays = 3,
                            HasNeutral = false,
                            Name = "Election Test 4",
                            StartDate = new DateTime(2014, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("40556dbd-b5ae-47af-89eb-32deee130dd9"),
                            DurationInDays = 3,
                            HasNeutral = false,
                            Name = "Election Test 5",
                            StartDate = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("42c5a090-b3bd-4b0b-9de4-48f987d8346e"),
                            DurationInDays = 3,
                            HasNeutral = false,
                            Name = "Election Test 6",
                            StartDate = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("442530b2-3e0a-4fc1-995d-1da1c6cb55cc"),
                            DurationInDays = 3,
                            HasNeutral = false,
                            Name = "Election Test 7",
                            StartDate = new DateTime(2017, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f8899970-5057-4a23-833c-dc75ee84c8d2"),
                            DurationInDays = 3,
                            HasNeutral = false,
                            Name = "Election Test 8",
                            StartDate = new DateTime(2018, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b6ea83b1-3cbe-47ed-bf25-9abc8dac9644"),
                            DurationInDays = 3,
                            HasNeutral = false,
                            Name = "Election Test 9",
                            StartDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("cfd1f2a9-3984-42a0-8ec1-26fd4eef0ead"),
                            DurationInDays = 3,
                            HasNeutral = false,
                            Name = "Election Test 10",
                            StartDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("bbcd22cb-dc43-4ea2-854c-acb61564699c"),
                            DurationInDays = 3,
                            HasNeutral = false,
                            Name = "Election Test 11",
                            StartDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b798676d-750e-4950-a527-5ccbc17004a4"),
                            DurationInDays = 3,
                            HasNeutral = false,
                            Name = "Election Test 12",
                            StartDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("33e5e889-f44b-461a-83c9-680f34f82e06"),
                            DurationInDays = 3,
                            HasNeutral = false,
                            Name = "Election Test 13",
                            StartDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.State", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("State");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fa9b72ee-dfcc-4353-b195-5c2855b1343f"),
                            Name = "Oran"
                        },
                        new
                        {
                            Id = new Guid("32065802-7f25-47bc-8987-dd4fdb2829c4"),
                            Name = "Meca"
                        },
                        new
                        {
                            Id = new Guid("3138e047-e80f-44a1-ae1d-96804784f807"),
                            Name = "Cairo"
                        },
                        new
                        {
                            Id = new Guid("33f88529-1a04-4d5e-84dc-135646948bc0"),
                            Name = "ElQuds"
                        },
                        new
                        {
                            Id = new Guid("918333ff-ac52-4424-a3d9-09bee4c39b91"),
                            Name = "Algiers"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Vote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Datetime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ElectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VoterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("ElectionId");

                    b.HasIndex("VoterId");

                    b.ToTable("Vote");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7c6fadf7-089b-4836-a849-1a81f2c0b84f"),
                            CandidateId = new Guid("8bc92480-c3d1-440d-86c4-a6a4ed89255a"),
                            Datetime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectionId = new Guid("c71e21c7-3c87-4aea-bf8d-2be8edc8722a"),
                            VoterId = new Guid("8dd6ebe1-e2e4-4555-ac61-9887cebebf61")
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Voter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("Voter");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0d925194-fee5-4750-a53c-b36a47afeeab"),
                            FirstName = "Hamza",
                            LastName = "Dahmoun",
                            StateId = new Guid("fa9b72ee-dfcc-4353-b195-5c2855b1343f"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("8dd6ebe1-e2e4-4555-ac61-9887cebebf61"),
                            FirstName = "Ikram",
                            LastName = "Dahmoun",
                            StateId = new Guid("fa9b72ee-dfcc-4353-b195-5c2855b1343f"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("df4b1285-b216-488c-88b7-0de75528f2fc"),
                            FirstName = "Ahmed",
                            LastName = "Mohamed",
                            StateId = new Guid("fa9b72ee-dfcc-4353-b195-5c2855b1343f"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("c81388cf-be3e-42fc-b791-02eccce16095"),
                            FirstName = "Mohamed",
                            LastName = "Zitouni",
                            StateId = new Guid("32065802-7f25-47bc-8987-dd4fdb2829c4"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("4ff2b64f-17fe-4621-9310-eeb59a9af847"),
                            FirstName = "Yasser",
                            LastName = "Zitouni",
                            StateId = new Guid("32065802-7f25-47bc-8987-dd4fdb2829c4"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("e61f81ab-a991-4298-b668-c973a5b75dc9"),
                            FirstName = "Larbi",
                            LastName = "Fkaier",
                            StateId = new Guid("32065802-7f25-47bc-8987-dd4fdb2829c4"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("1d6d6442-25ac-4cf9-aa44-0d91622a4927"),
                            FirstName = "Djamel",
                            LastName = "Tahraoui",
                            StateId = new Guid("32065802-7f25-47bc-8987-dd4fdb2829c4"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("62ae0555-718d-4623-a12a-7ae4a2e26aef"),
                            FirstName = "Sidahmed",
                            LastName = "Dahmoun",
                            StateId = new Guid("3138e047-e80f-44a1-ae1d-96804784f807"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("6c9de511-db59-4be8-9315-d58700ce10be"),
                            FirstName = "Bilal",
                            LastName = "Dahmoun",
                            StateId = new Guid("3138e047-e80f-44a1-ae1d-96804784f807"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("cd285ce6-b6e9-4933-8e07-6d50e0251788"),
                            FirstName = "Maria",
                            LastName = "Hafsa",
                            StateId = new Guid("33f88529-1a04-4d5e-84dc-135646948bc0"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("d454ae67-913e-4f7b-82c1-4da539737199"),
                            FirstName = "Brahim",
                            LastName = "Roudjai",
                            StateId = new Guid("33f88529-1a04-4d5e-84dc-135646948bc0"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("18537eea-e8f8-49cd-8ddf-10646c9a9f21"),
                            FirstName = "Amine",
                            LastName = "Brahem",
                            StateId = new Guid("33f88529-1a04-4d5e-84dc-135646948bc0"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("d789a80a-493f-4248-90b0-35edab1c3c63"),
                            FirstName = "Azzedine",
                            LastName = "Brahmi",
                            StateId = new Guid("3138e047-e80f-44a1-ae1d-96804784f807"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("71ad22cf-168a-40be-9867-4a7ebe34c339"),
                            FirstName = "Mohamed",
                            LastName = "Chikhi",
                            StateId = new Guid("918333ff-ac52-4424-a3d9-09bee4c39b91"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("783118b1-111d-4c6e-b75e-dcd721ccfc2c"),
                            FirstName = "Mahmoud",
                            LastName = "Dahmoun",
                            StateId = new Guid("918333ff-ac52-4424-a3d9-09bee4c39b91"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("0642267b-8df3-405d-b596-e50c2cdeefde"),
                            FirstName = "Lakhdar",
                            LastName = "Zitouni",
                            StateId = new Guid("918333ff-ac52-4424-a3d9-09bee4c39b91"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Candidate", b =>
                {
                    b.HasOne("WebApplication1.Models.Election", "Election")
                        .WithMany("Candidates")
                        .HasForeignKey("ElectionId");

                    b.HasOne("WebApplication1.Models.Voter", "VoterBeing")
                        .WithMany()
                        .HasForeignKey("VoterBeingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApplication1.Models.Vote", b =>
                {
                    b.HasOne("WebApplication1.Models.Candidate", "Candidate")
                        .WithMany("Votes")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.Election", "Election")
                        .WithMany("Votes")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.Voter", "Voter")
                        .WithMany("Votes")
                        .HasForeignKey("VoterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApplication1.Models.Voter", b =>
                {
                    b.HasOne("WebApplication1.Models.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
